#ifndef sp_menubg_h
#define sp_menubg_h

#include <PR/sp.h>

#define menubgTRUEIMAGEH	240
#define menubgTRUEIMAGEW	320
#define menubgIMAGEH	256
#define menubgIMAGEW	320
#define menubgBLOCKSIZEW	32
#define menubgBLOCKSIZEH	32
#define menubgSCALEX	1.0
#define menubgSCALEY	1.0
#define menubgMODE	SP_Z | SP_OVERLAP | SP_TRANSPARENT

// extern varaibles 
extern Bitmap menubg_bitmaps[];
extern Gfx menubg_dl[];

#define NUM_menubg_BMS  (sizeof(menubg_bitmaps)/sizeof(Bitmap))

extern Sprite menubg_sprite;

#endif 

#if 0	/* Image preview */
+------------------------------------------------+
|IIIIIIIIIIIIIIIIIIIII@@@@@@@@@@@@@@@@@@@@@@@@@@@|
|IIIIIIIIIIIIIII@IIIIII@@@@@@@@@@@@@@@@@@@@@@@@II|
|IIIIIIIIIIIIIII@IIIIIII@@@@@@@@@@@@@@@@@@@@@IIII|
|IIIIIIIIIIIIIII@@IIIIII@@@@@@@@@@@@@@@@@@@IIIIII|
|IIIIIIIIIIIIIIIIIIIIIIII@@@@@@@@IIIIIIIIIIIIIIII|
|IIIIIIIIIIIIIIIIIIIIIIII@@@@I@@IIIIIIIIIIIIIIIII|
|IIIIIIIIIIIIIIIIIIIIIIIIII@IIIIIIIIIIIIIIIIIIIII|
|IIIIIIIIIIIIIIII@IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII|
|@@@@@@IIIIIIIIIII@@@IIIIIIIIIIIIIIIIIIIIIIIIIIII|
|@@@@@@@@@@@@@IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII|
|@@@@@@@@@@@@@@@@@@@@I@@I@@@@@IIIIIIIIIIIIIIIIIII|
|@@I@@@@@@@@@@@@@@@@@I@@IIIIIIIIIIIIIIIIIIIIIIIII|
|IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII|
|IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII|
|@II@@@@@@@IIIII@IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII|
|IIIIIIII@@@IIIII@IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII|
|IIIIIII@@@II@@@IIIIIII@IIIIIIIIIIIIIIIIIIIIIIIII|
|IIII@@@@IIIIIIIIIIIIII@IIIIIIIIIIIIIIIIIIIIIIIII|
|II@@@IIIIIIIIIIIIIIIIII@IIIIIIIIIIIIIIIIIIIIIIII|
|@@@IIII@IIII@IIIIIIIIII@IIIIIIIIIIIIIIIIIIIIIIII|
|@IIIIIIIIII@IIIIIIIIII@@IIIIIIIIIIIIIIIIIIIIIIII|
|IIIIIIIIII@IIIIIIIIIII@IIIIIIIIIIIIIIIIIIIIIIIII|
|IIIIIIIII@IIIIIIIII@@@I@IIIIIIIIIIIIIIIIIIIIIIII|
|IIIIIIII@IIIIIIIIIII@I@I@IIIIIIIIIIIIIIIIIIIIIII|
+------------------------------------------------+
#endif

